### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by smartey**
Quick links Dashboard translation fix

### CODE REVIEW

**Comment by vbezruchkin** [comment]
Hi,

Thanks for your request. Sorry, cannot accept it right now as it affects a lot of functionality including all plugins / package, which might be a pain for existing customers. We need to work out some sort of temp compatibility with existing plugins.

We will get in touch soon.

**Comment by vbezruchkin** [comment]
Sorry, cannot accept it.

'admin_actions' is used for admin dashboard action buttons on top right. We already have a temp compatibility fix, here is the code:
`
'title' => iaLanguage::get($entry['text'], $entry['text']),
`
So you can pass phrase key there, and then it will be used. If not, non-translated value will be used.

Regarding commit:
You added keys, but there are no phrases there for these keys.
You also modified menu display, but proper languages are already used in getAdminMenu() method in ia.core.smarty.php file.

Thanks

**Comment by smartey** [comment]
Hi Vasily,

no problem, sorry for inconvenience, still learning and not knowing so much about Subrion code config.

All the plugins I use seem to work fine with the change I created. Will my change break plugins or is it mainly too much work with regard to existing users/plugins?

No problem with other (temp) work around, are you guys already working on another multi language fix or can I try figuring out a work-around that would not affect existing plugins in the way they are with my current fix?


Thanks!

Eric

Op 16-1-2017 om 06:54 schreef Vasily Bezruchkin:

Hi,

Thanks for your request. Sorry, cannot accept it right now as it affects a lot of functionality including all plugins / package, which might be a pain for existing customers. We need to work out some sort of temp compatibility with existing plugins.

We will get in touch soon.

**Comment by vbezruchkin** [comment]
Hi Eric

First of all thanks for your contribution. I just accepted some of your merge requests. Anyhow, let's wait for the solution. I suspect there should be a more proper way in system to handle phrases for admin actions. 
Probably we should tie phrases to action keys directly to avoid duplication. If we check records now, we can see we have many same values for both name & text values. It makes no sense as we can use name as phrase key. So probably we can get rid of duplication.

Your changes work find and don't break the plugins. I'm not just sure it's the final way to handle actions phrases so I wanted to prevent you from doing this as it might be changed.

So give us some time and we will get back with the solution.

Thanks, @smartey

**Comment by smartey** [comment]
Happy to contribute :)
I agree, there should be a better way. I chose the text field because it was already used for text display and I was fairly sure that text field change would most likely not cause issues for my vanilla install.

One final question, the changes I created for Events plugin (similar RSS Feed fix as Blog, Fix for Map in Admin, Event body Multi Language fix, Maps url fix) are still relevant I think but there is also the Multi lanuage fix in same commit which is unwanted. What can I do best, create a new pull request with only the changes that are relevant?

Thanks!

**Comment by vbezruchkin** [comment]
Hi, 

Please recheck https://github.com/intelliants/subrion/commit/02bc5d31dfbfff51592b21c07d4b3737ab96a8d5 

Now actions are tied to names, so you only need to create a phrase for your unique admin_action record, and it will be used. It's compatible with all the plugins & packages we already have.

Yes, please. Create a new pull request the changes.

Thanks

**Pull request closed without merging**
